apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
  labels:
    app: APP_NAME
spec:
  replicas: NO_OF_REPLICAS
  selector:
    matchLabels:
      app: APP_NAME
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - BACKEND_APP_NAME
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: APP_NAME
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 150
          periodSeconds: 10

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: APP_NAME
#  labels:
#    app: APP_NAME
#spec:
#  selector:
#    app: APP_NAME
#  ports:
#    - name: http
#      protocol: TCP
#      port: 80
#      targetPort: 3000
#  type: ClusterIP
